### ISSUE TITLE
[visual-recognition] Build Failed with exit code 65

### ISSUE THREAD

**Issue by johnlpm** [watson-developer-cloud/swift-sdk#839] opened 2018-06-21 03:10 UTC
Archived Failed. Please see the error log below: 

_error: type 'Face' does not conform to protocol 'Decodable'
public struct Face: Decodable {
              ^
Swift.Decodable:9:12: note: protocol requires initializer 'init(from:)' with type 'Decodable'
    public init(from decoder: Decoder) throws
           ^
/Users/awsys-dev2/Desktop/ChatApp/Carthage/Checkouts/swift-sdk/Source/VisualRecognitionV3/Models/Face.swift:38:16: note: cannot automatically synthesize 'Decodable' because 'identity' does not have a matching CodingKey and does not have a default value
    public var identity: FaceIdentity?
               ^_

**Comment by mkistler** [comment] 2018-06-21 12:30
@johnlpm Can you pls provide the versions of Xcode and Swift you are using, and whether you are building on MacOs or Linux?

**Comment by bourdakos1** [comment] 2018-06-29 16:43
@mkistler I've also been seeing this issue, I can't reproduce it on my machine, but a majority of the people at a few workshops we've been doing have had the problem. The project fails to build when using Carthage as well as when manually building the project. I have Xcode 9.4 (and it works). I think most people with the issue have Xcode 9.4.1

**Comment by mkistler** [comment] 2018-06-30 02:13
Should be fixed in v0.29.0 (released today).

**Comment by mkistler** [comment] 2018-06-30 12:39
Elaborating a bit:  according to `man xcodebuild`:
> xcodebuild exits with codes defined by sysexits(3).

and `man 3 sysexits` says:
>      EX_DATAERR (65)       The input data was incorrect in some way.  This should only be used for user's data and not system files.

So it appears that 65 is the expected return code whenever any of the tests fail -- which unfortunately happens semi-regularly because most of the tests hit live service instances.

What _should be_ fixed in v0.29.0 is that _if all the tests pass_, the xcodebuild rc should be 0 --previously it was 66, because of a missing shared scheme file.

**Comment by bourdakos1** [comment] 2018-06-30 14:38
Awesome, thanks :)

I updated to Xcode 9.4.1 and everything is still working for me. I have another workshop on Monday so I'll keep you posted on how that all goes. Thanks again for the help!

**Comment by johnlpm** [comment] 2018-07-02 08:22
Sorry for late response, I'm using objective C on MacOS, I use the old version of SDK and it's working fine right now ..

**Comment by bourdakos1** [comment] 2018-07-02 11:02
Building with Carthage worked for 100% of the people at our workshop today (about 30 participants). Thanks for all the help :)

**Closed** 2018-07-07 14:13 UTC

**Comment by addu1** [comment] 2018-10-29 06:49
I'm trying to install using carthage in a react native project.
Xcode Version 9.1 
Carthage Version 0.31.1
I get the following error:

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/macname/Desktop/REACT_NATIVE/myreactnativeproject/ios/Carthage/Checkouts/swift-sdk/WatsonDeveloperCloud.xcodeproj -scheme VisualRecognitionV3 -configuration Release -derivedDataPath /Users/macname/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/swift-sdk/0.36.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/gz/9g75r3m148950b69mz7q4h0r0000gn/T/swift-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/macname/Desktop/REACT_NATIVE/myreactnativeproject/ios/Carthage/Checkouts/swift-sdk)
