### ISSUE TITLE
[Conversation] Error while decoding Json in Swift

### ISSUE THREAD

**Issue by KopalKothari** [watson-developer-cloud/swift-sdk#585] opened 2017-02-27 12:59 UTC
I am working on Swift 3

[SwiftConversationPrj.zip](https://github.com/watson-developer-cloud/swift-sdk/files/803676/SwiftConversationPrj.zip)

 + Conversation (watson-developer-cloud/swift-sdk). The application gets reply from Conversation service as json but it throws an error while decoding the Json. Json that it is trying to decode is :
```swift
context =     {
       "conversation_id" = "8165b98e-8cae-4ec1-a448-f8b0761c0c62";
       "default_counter" = 0;
       system =         {
           "dialog_request_counter" = 1;
           "dialog_stack" =             (
               root
           );
           "dialog_turn_counter" = 1;
       };
   };
   entities =     (
   );
   input =     {
   };
   intents =     (
   );
   output =     {
       "log_messages" =         (
       );
       "nodes_visited" =         (
           "node_1_1467221909631"
       );
       text =         (
           "Hi. It looks like a nice drive today. What would you like me to do? "
       );
   };
}
```
And the error it throws is: RestKit.JSON.Error.unexpectedSubscript(Swift.String) for Json part:
 ```
"dialog_stack" =             (
               root
           );
root should be surrounded by "". 
```
Please confirm is this is a bug.

- [ ] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [ ] Steps to reproduce
- [ ] Expected behavior
- [ ] Actual behavior
- [ ] Xcode version 8.2.1
- [ ] ios-sdk version
- [ ] ios version you are targeting

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title starting with the service name
- [ ] A description of the problem you're trying to solve
- [ ] A suggested solution if possible

**Comment by KopalKothari** [comment] 2017-02-28 22:52
Can you please let me know if more information is needed to reproduce the issue. Thanks!

**Comment by sccheng** [comment] 2017-03-01 15:57
Hi @KopalKothari, I'm looking into this today. I'll let you know if I run into any problems reproducing your issue!

**Comment by sccheng** [comment] 2017-03-01 20:10
Hi @KopalKothari,

So I took a look, and it turns out that as of September 20, 2016, the Conversation service was updated so that the Context model's `dialog_stack` is no longer an array of strings. It's now an array of JSON objects. This is documented in the [release notes](http://www.ibm.com/watson/developercloud/doc/conversation/release-notes.html#20-september-2016).

The reason that you're seeing the `unexpectedSubscript(Swift.String)` error is because our SDK is expecting an array of JSON objects rather than an array of strings, like you're receiving right now. You're probably receiving the old model because you currently specify "2016-07-11" as your version date.

You can fix the error by updating your main.swift so that, on line 10, you're using version "2016-09-20" or later.

As a side note, thank you very much for attaching your project, it was extremely helpful in the debugging process!! I do want to remind you to make sure you reset your credentials though, as your credentials were attached in the file!

I'll go ahead and close this issue now, since I believe that updating your version date will fix the errors you're seeing.

**Closed by sccheng** 2017-03-01 20:10 UTC

**Comment by KopalKothari** [comment] 2017-03-02 04:44
Thanks Stephanie for the help! The error is no more there once I change the version. Thanks!
