### ISSUE TITLE
[visual-recognition] VisualRecognitionV3 Error with Paid Credentials 

### ISSUE THREAD

**Issue by ntwood** [watson-developer-cloud/swift-sdk#622] opened 2017-04-25 20:42 UTC
The Bluemix user is making a call to VisualRecognitionV3 function using Swift, and is receiving the following error:
 
Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}

The call returns the expected result when he uses his free credentials; when he makes the exact same call with his paid credentials the call fails. Here is what he is passing to Watson:
 
//With paid API key the following returns the errror:
Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}
func fetchSimilarImages(URL: URL) {
    let visualRecognition = VisualRecognition(apiKey: WatsonInfo.paidKey.rawValue, version: WatsonInfo.version.rawValue)
    let failure = {(error: Error) in
        print("Error Finding Similar Images")
        print(error)
    }
    visualRecognition.findSimilarImages(toImageFile: URL, inCollectionID: WatsonInfo.cineFrameMaster.rawValue, limit: 100, failure: failure) { (images) in
        print("Found similar images")
        let similar = images.similarImages
        print(similar)
    }
}

I spoke with the Watson team on Slack, and they directed me to this repo.

**Comment by schen22** [comment] 2017-04-25 20:57
Which version of the service are they using, and do their paid credentials work when they use a `curl` command similar to the following? 

curl -X POST -F "images_file=@https://raw.githubusercontent.com/watson-developer-cloud/java-sdk/master/tests/src/test/resources/visual_recognition/car.png" "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key={INSERT_API_KEY_HERE}&version=2016-05-20"

**Comment by schen22** [comment] 2017-04-25 21:04
Which version of the service are they using, and do their paid credentials work when they use a `curl` command similar to the following?

`curl -X GET "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key={INSERT_API_KEY_HERE}&url={https://www.whitehouse.gov/sites/whitehouse.gov/files/images/Administration/People/president_official_portrait_lores.jpg}&version=2015-12-02"`

**Comment by tuckermacdonald** [comment] 2017-04-26 19:59
@schen22 - Looks like I originally created this ticket. I've been using the latest version (V3 & always updating the date). My service credentials have been working fine for classifying images, but not for finding similar ones. Not sure if the `curl` command you referenced would affect a similar image request?

**Comment by sccheng** [comment] 2017-04-26 20:45
Hi @tuckermacdonald,

Hmm, can you go ahead and try this curl command, then?
`curl -X POST -F "image_file=@silver_dress2.jpg" "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/collections/{collection_id}/find_similar?limit=100&api_key={api-key}&version=2016-05-20"`

Either that, or try the `findSimilarImage` call in something like [Postman](https://www.getpostman.com/). Details for the findSimilarImages endpoint can be found here in the [documentation](https://www.ibm.com/watson/developercloud/visual-recognition/api/v3/#find_similar).

We want to first make sure that the issue you're seeing is caused by the SDK, and not your new instance of the service.

**Comment by tuckermacdonald** [comment] 2017-04-27 00:07
@schen22 - that command (with my collection ID & api-key) returns the following error:
```
{
  "status": "ERROR",
  "statusInfo": "invalid-api-key"
}
```
Tried the request with both my free & paid keys/collections as well, with the same response. Not sure if there was any user error or not with submitting the request..? Let me know if there is anything else to troubleshoot for determining the status of my new service.

**Comment by sccheng** [comment] 2017-04-27 14:59
Hi @tuckermacdonald,

This might be a silly question, but did you make sure to remove the brackets `{}` when you replaced the placeholders with your collection_id/api-key/your-image.extension? I always forget to, just wanted to make sure you did that!!

**Comment by tuckermacdonald** [comment] 2017-04-28 12:30
Hey @schen22 - thanks for the reminder! I hadn't removed them.

So, upon making the request correctly from Postman:

My paid credentials return the following:
`If you are seeing this message, you are likely making an excessive number of concurrent HTTP connections to this service.  Please check the concurrency limits for your assigned service tier.
`

My free credentials properly return a list of similar images from one of my collections.

**Comment by sccheng** [comment] 2017-04-28 16:16
Hi @tuckermacdonald,

Looks like this might not be an issue with the SDK... My hunch is that this is the same error you're seeing in the SDK, but we aren't properly parsing that error message, so instead you see the `Invalid value around character 0` error message.

Please reach out to the Bluemix support team and let them know that you're seeing this error. 

I'll close this issue for now, since I don't believe that this is an issue on our end. Please feel free to reopen it or create a new one if you learn otherwise!

**Closed by sccheng** 2017-04-28 16:16 UTC
