### ISSUE TITLE
Speech-To-Text to support Mac OSX?

### ISSUE THREAD

**Issue by busywq** [watson-developer-cloud/swift-sdk#856] opened 2018-07-23 06:21 UTC
Is there any plan to support Mac OSX? Now I'm tring to find a solution of STT for Mac OSX app, but seems only IOS is supportted now.

**Comment by AnthonyOliveri** [comment] 2018-07-24 16:39
Hi @busywq. We do intend to add support for macOS in the future, but we don't yet have a timeline for when it will be implemented. Our goal is to have macOS supported by the 1.0 release.

**Comment by AnthonyOliveri** [comment] 2018-07-24 16:40
This thread may help to see if you can get STT working for macOS in the meantime: https://github.com/watson-developer-cloud/swift-sdk/issues/129.

**Comment by mkistler** [comment] 2019-03-10 20:31
Duplicate of #129

**Closed** 2019-03-10 20:31 UTC
