### ISSUE TITLE
[Image Recognition] Always returning 400 (null)

### ISSUE THREAD

**Issue by vincent-paing** [watson-developer-cloud/swift-sdk#924] opened 2018-12-05 07:05 UTC
Xcode Version : 10.1 (10B61)
iOS Version : 12.1
Simulator : iPhone XR - 12.1

Step to reproduce:
1.  Pick an image from library
2. Pass that image into classify
3. Wait for a while

Here's the code snippet for reproduction
```swift
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
        guard let pickedImage = info[UIImagePickerController.InfoKey.originalImage] as? UIImage else {
            fatalError("Cannot get picked image")
        }
        
        imagePicker.dismiss(animated: true, completion: nil)
        
        let visualRecognition = VisualRecognition(version: version, apiKey: apiKey)
        
        let failure = { (error: Error) in print(error) }
        
        visualRecognition.classify(image: pickedImage, failure: failure) { (classifiedImages) in
            //This does not get called
            print(classifiedImages)
        }
        
    }
```

This is the error log:
```
Error Domain=com.ibm.watson.developer-cloud.VisualRecognitionV3 Code=400 "(null)"
2018-12-05 13:34:30.124309+0630 IBMSeeFood[39699:6251566] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe9cff0ac40] get output frames failed, state 8196
2018-12-05 13:34:30.124946+0630 IBMSeeFood[39699:6251566] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe9cff0ac40] get output frames failed, state 8196
2018-12-05 13:34:30.125839+0630 IBMSeeFood[39699:6251566] TIC Read Status [1:0x0]: 1:57
2018-12-05 13:34:30.126005+0630 IBMSeeFood[39699:6251566] TIC Read Status [1:0x0]: 1:57
2018-12-05 13:34:30.126622+0630 IBMSeeFood[39699:6251566] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x7fe9cfc18240] get output frames failed, state 8196
2018-12-05 13:34:30.127396+0630 IBMSeeFood[39699:6251566] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x7fe9cfc18240] get output frames failed, state 8196
2018-12-05 13:34:30.127773+0630 IBMSeeFood[39699:6251566] TIC Read Status [2:0x0]: 1:57
2018-12-05 13:34:30.128053+0630 IBMSeeFood[39699:6251566] TIC Read Status [2:0x0]: 1:57
```

**Comment by AnthonyOliveri** [comment] 2018-12-05 20:34
I tried reproducing this exactly as you described, and it worked fine for me. Unfortunately, that error message `Code=400 "(null)"` is pretty useless. My first guess would be to verify that you have the correct `apiKey` in the `VisualRecognition` initializer. I would expect a bad `apiKey` to cause a `401 unauthorized` response, but it's still worth a try. 

What are you using for the `version` parameter?

**Comment by vincent-paing** [comment] 2018-12-06 05:17
@AnthonyOliveri I'm sending in the date in yyyy/mm/dd format, for example "2018-12-6".

**Comment by mkistler** [comment] 2018-12-06 14:16
You need to use an explicit two digit day, so "2018-12-6" is not valid.  It must be "2018-12-06".

**Comment by Matthieu-Malyga** [comment] 2019-01-12 12:45
I had the exact same issue with the func classify(imagesFile: URL? = default, acceptLanguage: String? = default ......) method.

First my date was not formatted correctly (my fault). I suggest using a little var that gets the current date correctly formatted instead of hard coding it:

var date: String {
        let dateFormatter = ISO8601DateFormatter()
        dateFormatter.formatOptions = [.withFullDate, .withDashSeparatorInDate]
        return dateFormatter.string(from: Date())
    }

Then I found out that you have to specify the "acceptLanguage" parameter of the classify method (especially on a physical device ... it would work fine in the simulator which I didn't test because of the camera need). Which is even better since I'm French and I can receive the translated results instead of receiving them in English :)

**Comment by vlad-racu** [comment] 2019-01-13 12:00
@Matthieu-Malyga thank you for your temporary solution. I had my whole Bachelor's degree project based around IBM Visual Recognition and it suddenly stopped working for me.
Adding that extra language parameter did the magic for me.

Still, this thread should be kept alive. I can confirm both my simulators and my physical devices got the 400 response when using the "classify" method without that language parameter. It used to work without that parameter in the past.

**Comment by mkistler** [comment] 2019-01-13 12:13
Which version of the Watson Swift SDK are you using?

**Comment by vlad-racu** [comment] 2019-01-13 14:13
The first time I've encountered the problem, I was on 1.0.0
While trying to solve the issue yesterday, I've updated to 1.2.0
Both versions give me the same result

**Comment by mkistler** [comment] 2019-01-13 16:33
I have reproduced this problem and tracked it to a problem in the service.  I've opened an issue with the service team and will report back when it has been addressed.

**Comment by mkistler** [comment] 2019-03-10 21:41
Service team reports that this is now fixed in production. Please reopen if you find otherwise.

**Closed by mkistler** 2019-03-10 21:41 UTC

**Comment by marcelkalveram** [comment] 2019-05-18 11:08
If anyone else runs into this problem.
I figured out what my issue was after writing the output of the error object to the console:

```..."description": RestKit.JSON.string("**Image is too large**"), ...```

Seems like the simulator default images are gigantic. My solution was to [downsample](https://stackoverflow.com/questions/31314412/how-to-resize-image-in-swift) before sending it to the IBM cloud.
