### ISSUE TITLE
[speech-to-text] Memory leak in SpeechToTextRecorder.swift `AudioQueueInputCallback`

### ISSUE THREAD

**Issue by teddynewell** [watson-developer-cloud/swift-sdk#571] opened 2017-01-30 21:25 UTC
## Problem Summary
Using the streaming transcription in `SpeechToTextV1`, I see a steady climb in memory usage.  Investigation using Instruments for profiling indicates the memory allocation is from line 53 in SpeechToTextRecorder.swift:
```
let pcm = Data(bytes: buffer.mAudioData, count: Int(buffer.mAudioDataByteSize))
```

## Suggested Solution
Wrapping the subsequent code that uses `pcm` in an autorelease pool prevents the steady climb in memory usage:
```
let pcm = Data(bytes: buffer.mAudioData, count: Int(buffer.mAudioDataByteSize))
autoreleasepool() { _ in
  audioRecorder.onMicrophoneData?(pcm)
}
```
This workaround is inspired by the similar `AudioQueueInputCallback` setup in [wit.ai's WITRecorder.m](https://github.com/wit-ai/wit-ios-sdk/blob/master/Wit/WITRecorder.m).

**Potential Downside**
The autorelease pool has a small negative impact on performance, which is important to consider in realtime audio callbacks.  In my testing of the proposed solution, the performance impact is not enough to affect the realtime streaming and recording functionality. 

## Steps to Reproduce
1. Set up steaming `SpeechToTextSession` as described in the ReadMe's [Session Management and Advanced Features](https://github.com/watson-developer-cloud/swift-sdk#session-management-and-advanced-features)
2. Start streaming

**Expected Behavior**
After streaming begins, memory usage of the `SpeechToTextSession` should be relatively stable over time.

**Unexpected Behavior**
After streaming begins, memory usage of `SpeechToTextSession` steadily rises until streaming stops.  Starting streaming again continues to increase the memory usage continually, as in the following screenshot:
<img width="740" alt="steady memory climb" src="https://cloud.githubusercontent.com/assets/770729/22441775/a3ee3a3a-e6ed-11e6-905f-2bde58f877d3.png">

**Xcode Version:** 8.2.1

**ios-sdk/swift-sdk Version:** Issue verified on both swift-sdk v0.13.2 and ios-sdk v0.8.2

**Target iOS Version:** Issue verified on both iOS 10.2, 9.0

### When reporting a bug, please be sure to include the following:

- [x] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [x] Steps to reproduce
- [x] Expected behavior
- [x] Actual behavior
- [x] Xcode version
- [x] ios-sdk version
- [x] ios version you are targeting

### When you open an issue for a feature request, please add as much detail as possible:
- [x] A descriptive title starting with the service name
- [x] A description of the problem you're trying to solve
- [x] A suggested solution if possible

**Comment by sccheng** [comment] 2017-02-22 20:44
Hey @teddynewell,

Thanks for such a descriptive issue! I've started looking into this issue and your PRs. When testing your fix, I did indeed see that the memory usage stayed constant, as opposed to the constant climb before.

Before I merge your change, I was wondering what your reasoning was behind using `autoreleasepool`. I haven't worked with autorelease pools before and was trying to wrap my head around the concept. This autorelease pool block that you created, does this just specify that any temporary variables created inside the block must be released at the end of the block? With ARC, wouldn't these variables have been released automatically anyway?

I'm trying to understand why, if the culprit of the steady increase of memory allocation is the line `let pcm = Data(bytes: buffer.mAudioData, count: Int(buffer.mAudioDataByteSize))`, the solution is to wrap the next line of code `audioRecorder.onMicrophoneData?(pcm)` in an autorelease pool would solve the problem. Why not include both lines in the block?

**Comment by teddynewell** [comment] 2017-02-22 23:55
Hi @sccheng, thanks for taking a look at this!

You are correct that the autorelease pool block pushes a memory-managed context that is cleaned up at the end of the block.  ARC _should_ be releasing the variables in this real-time audio callback anyway, but it looks like sending the `pcm` `Data` object to the `onMicrophoneData` block is the specific issue preventing ARC from doing what we expect.  The compiler may not be able to identify the object ownership correctly, although unfortunately I cannot point to any documentation on why this might be the case.

As to your second question about wrapping the `let pcm = Data(...)` initialization within the autorelease pool block, I think this would work just fine (although I haven't tested it). I imagine it would also help self-document the special care needed for memory handling here, in case the pcm data needs to be used in another callback in future.  I chose to keep the initialization outside the block following the example in [WITRecorder.m](https://github.com/wit-ai/wit-ios-sdk/blob/master/Wit/WITRecorder.m), which alternatively self-documents the memory leak is specific to the usage of `pcm` in the callback invocation.  Ultimately the choice is yours, whichever you think is most clear.

**Comment by sccheng** [comment] 2017-02-23 22:55
Hi @teddynewell,

Ahh interesting, okay. Thanks for explaining that, I appreciate it :) What you've said seems pretty reasonable - it makes sense to me!

Perhaps a route we could take now is to wrap both lines in the autorelease pool block, so that it is a bit more understandable - and maybe add a short comment before the block, to specify that it's needed so we can ensure that the pcm data is being released in a timely manner. What do you think?

Other than that, I think your code looks good! Through testing, it seems to work as intended.

**Comment by sccheng** [comment] 2017-02-28 19:22
Hey @teddynewell,

Just wanted to check back in and see if you'd be able to make those changes to your pull request. Again, I was thinking that we could add a short comment to the beginning of the autorelease pool block, perhaps, and move both lines into the block. 

Let me know what you think!

**Comment by teddynewell** [comment] 2017-02-28 19:24
Yes, I can definitely do that. I'll update the pull request later today :)

**Comment by teddynewell** [comment] 2017-02-28 22:44
@sccheng #572 updated per your suggestions.

**Comment by sccheng** [comment] 2017-03-01 20:23
Yay, thanks @teddynewell!! :)

**Closed** 2017-03-01 20:24 UTC
