### ISSUE TITLE
Speaker labels not returned when processing interim results

### ISSUE THREAD

**Issue by shun-j** [watson-developer-cloud/swift-sdk#645] opened 2017-07-17 17:53 UTC
This capability works on web demo, and it is working well using the java client SDK.

- Steps to reproduce
When use the following setting, the sdk will provide continuously interim transcripts but does not provide the speaker labels.
        var settings = RecognitionSettings(contentType: .opus)
        settings.interimResults = false
        settings.continuous = true
        settings.speakerLabels = true
        settings.timestamps = true

- Expected behavior
Receive the speaker labels along with the interim transcript.
- Actual behavior:
The interim transcript returns but does not receive speaker labels data.
- Xcode version
Xcode 8.3.3
- ios-sdk version
iOS 10
- ios version you are targeting
iOS 10

**Comment by Gurdev-Singh** [comment] 2017-09-04 11:32
I am also facing the same issue with not being able to receive speakerLabels.

Is there any update on this issue?

**Comment by glennrfisher** [comment] 2017-09-05 19:18
I tried to track this down, but couldn't find the root cause. I'm planning to work on Xcode 9 / Swift 3.2 updates first and hope to find time to fix this problem soon.

**Comment by Gurdev-Singh** [comment] 2017-10-04 06:50
Is there any update regarding this issue? Speaker labels array is returned but they are smaller in numbers and received with an initial 61 seconds of delay.

**Comment by glennrfisher** [comment] 2017-10-04 22:04
Hi @Gurdev-Singh. I haven't gotten a chance to look at this yet, but expect to publish a fix in the next 2 weeks. Sorry for the delay!

**Comment by Gurdev-Singh** [comment] 2017-10-18 10:45
Hi @glennrfisher  - Did you got the chance to look into this issue and its related fix?

**Comment by glennrfisher** [comment] 2017-10-18 21:35
Hi @Gurdev-Singh. The fix was actually merged into the `master` branch earlier this week with #683. Just waiting to resolve an issue with Visual Recognition and then we'll publish the updates in an official release.

To use the fix in the meantime, you can update your `Cartfile` to pull from the master branch:

```
github "watson-developer-cloud/swift-sdk" "master"
```

**Comment by glennrfisher** [comment] 2017-10-24 19:05
The fix is included with release v0.19.0 of the Swift SDK. Hope that helps!

**Closed by glennrfisher** 2017-10-24 19:05 UTC
